// generated by "sampctl package generate"

#include "samp-tpi.inc"

main() {
	// Use /test command (duh)
}

public OnGameModeInit()
{
	SendRconCommand("hostname samp-tpi Test Gamemode");
	SetGameModeText("Testing samp-tpi");
	ShowPlayerMarkers(true);
	ShowNameTags(true);	
	return 1;
}

public OnPlayerRequestClass(playerid, classid)
{
	SetSpawnInfo(playerid, NO_TEAM, 1, 1530.5607, -1680.9048, 13.3828, 0.1423, 22, 120, 27, 60, 41, 5678);
	SpawnPlayer(playerid);

	SendClientMessage(playerid, -1, "Straight to the point: Use /test command.");
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/test", true))
	{
		if(IsPlayerInvisible(playerid))
		{
			SendClientMessage(playerid, -1, "You are now visible to other players.");
			TogglePlayerInvisibility(playerid, false);
		}
		else
		{
			SendClientMessage(playerid, -1, "You are now Invisible to other players.");
			TogglePlayerInvisibility(playerid, true);
		}
		return 1;
	}
	return 0;
}

public OnPlayerSpawn(playerid)
{
	SetPlayerInterior(playerid,0);
	TogglePlayerClock(playerid,0);
	return 1;
}